name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt

      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: -- --check

  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt
          
      - name: Build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --verbose

      - name: Run tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --verbose
