[package]
name = "simple_bot_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "1.0"
quote = "*"
proc-macro2 = "1.0"
proc_qq = "0.1.34"
anyhow = "*"
serde = "*"
serde_json = "*"

[lib]
proc-macro = true