[package]
name = "simple_bot_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0.99", features = ["full"] }
quote = "1.0.21"
proc_qq = "0.1.15"
anyhow = "1.0.63"
serde = "1.0.144"
serde_json = "1.0.85"

[lib]
proc-macro = true